"""
YamGuard - Application Constants
"""

import os

# Application Info
APP_NAME = "YamGuard"
APP_VERSION = "1.0.0"
APP_BUILD = "2024.1"
APP_DESCRIPTION = "Smartphone-Based Hyperspectral Imaging for Early Detection of Fungal Infection in Yam Tubers"
APP_AUTHOR = "YamGuard Team"
APP_COPYRIGHT = "© 2024 YamGuard. All rights reserved."

# Paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
IMAGES_DIR = os.path.join(ASSETS_DIR, "images")
ICONS_DIR = os.path.join(ASSETS_DIR, "icons")
LOGO_DIR = os.path.join(ASSETS_DIR, "logo")
DATABASE_DIR = os.path.join(BASE_DIR, "database")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")
UPLOADS_DIR = os.path.join(BASE_DIR, "uploads")
EXPORTS_DIR = os.path.join(BASE_DIR, "exports")

# Database
DB_NAME = "yamguard.db"
DB_PATH = os.path.join(DATABASE_DIR, DB_NAME)

# Hyperspectral Configuration
SPECTRAL_RANGE_START = 400  # nm
SPECTRAL_RANGE_END = 1000   # nm
SPECTRAL_BANDS = 128
SPECTRAL_RESOLUTION = (SPECTRAL_RANGE_END - SPECTRAL_RANGE_START) / SPECTRAL_BANDS

# Key spectral wavelengths for fungal detection (nm)
KEY_WAVELENGTHS = {
    "chlorophyll_a": 675,
    "chlorophyll_b": 650,
    "carotenoid": 470,
    "water_band": 970,
    "nir_plateau": 800,
    "red_edge": 720,
}

# Infection severity levels
SEVERITY_LEVELS = {
    "Healthy": {"code": "H", "threshold": 90.0, "color": "#22C55E"},
    "Level 1 - Early Infection": {"code": "L1", "threshold": 75.0, "color": "#F59E0B"},
    "Level 2 - Moderate Infection": {"code": "L2", "threshold": 60.0, "color": "#F97316"},
    "Level 3 - Severe Infection": {"code": "L3", "threshold": 40.0, "color": "#DC2626"},
    "Level 4 - Critical": {"code": "L4", "threshold": 0.0, "color": "#7F1D1D"},
}

# Classification simulation probabilities
CLASSIFICATION_PROBABILITIES = {
    "Healthy": 0.60,
    "Level 1 - Early Infection": 0.25,
    "Level 2 - Moderate Infection": 0.15,
}

# Image Processing
CAPTURE_RESOLUTION = (1920, 1080)
PROCESSING_RESOLUTION = (640, 480)
JPEG_QUALITY = 95
SUPPORTED_IMAGE_FORMATS = [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]

# Machine Learning
CONFIDENCE_THRESHOLD = 85.0
MODEL_INPUT_SIZE = (224, 224)
FEATURE_VECTOR_SIZE = 128
PCA_COMPONENTS = 3

# Scan workflow steps
SCAN_STEPS = [
    "Reference Capture",
    "Tuber Positioning",
    "Spectral Acquisition",
    "Processing",
]

# Processing stages
PROCESSING_STAGES = [
    "Calibration",
    "Noise Reduction",
    "Segmentation",
    "Feature Extraction",
    "Classification",
]

# UI Configuration
ANIMATION_DURATION = 0.3
TOAST_DURATION = 3.0
DIALOG_RADIUS = 16
CARD_RADIUS = 12
BUTTON_RADIUS = 8

# Network (for future online sync)
API_BASE_URL = "https://api.yamguard.com/v1"
API_TIMEOUT = 30
SYNC_INTERVAL = 3600  # seconds

# Security
SESSION_EXPIRY_HOURS = 24
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30

# Report Configuration
REPORT_HEADER = "YamGuard - Agricultural Diagnostic Report"
REPORT_FOOTER = "Generated by YamGuard AI System"
COMPANY_ADDRESS = "Agricultural Research Division"
COMPANY_CONTACT = "support@yamguard.com"

# Export formats
EXPORT_FORMATS = {
    "pdf": "PDF Document",
    "csv": "CSV Spreadsheet",
    "json": "JSON Data",
}

# User roles
USER_ROLES = {
    "farmer": "Farmer",
    "researcher": "Researcher",
    "extension_officer": "Extension Officer",
    "admin": "Administrator",
}
